apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "personal-website.fullname" . }}-nginx
data:
  nginx.conf: |-
  {{- .Files.Get "files/nginx.conf" | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "personal-website.fullname" . }}-nginx-confd
data:
  default.conf: |-
    {{- .Files.Get "files/default.conf" | nindent 4 }}
  {{- if .Values.internalTLS }}
  ssl.conf: |-
    {{ .Files.Get "files/ssl.conf" | nindent 4 }}
  {{- end }}

