apiVersion: v1
kind: Service
metadata:
  name: {{ template "personal-website.fullname" . }}
  labels:
    app: {{ template "personal-website.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
   - name: http
     port: {{ .Values.service.externalPort }}
     targetPort: {{ .Values.service.internalPort }}
     protocol: TCP
    {{- if .Values.internalTLS }}
   - name: https
     port: 443
     targetPort: 443
     protocol: TCP
    {{- end }}
  selector:
    app: {{ template "personal-website.name" . }}
    release: {{ .Release.Name }}
