apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: personal-website
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
  - hosts:
    - "tyler.staplerstation.com"
    secretName: personal-website-tls
  rules:
    - host: tyler.staplerstation.com
      http:
        paths:
          - backend:
              serviceName: personal-website
              servicePort: 80
            path: /
---
kind: Service
apiVersion: v1
metadata:
  name: personal-website
spec:
  selector:
    app: personal-website
  ports:
  - protocol: TCP
    port: 80
