name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Bazel
        uses: bazelbuild/setup-bazelisk@v3

      - name: Build Site
        run: bazel build //:site_optimized

      - name: Prepare Deployment Directory
        run: |
          mkdir -p dist
          tar -xf bazel-bin/site_optimized_dir.tar -C dist

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=personal-website --commit-hash=$GITHUB_SHA --branch=$GITHUB_REF_NAME
